### ISSUE TITLE
Unable to Install/Compile

### ISSUE THREAD

**Issue by driftavalii** [blm768/pg-libphonenumber#9]
Following the instructions, I get the following error:
```
sudo make install
[sudo] password for dude: 
/bin/mkdir -p '/usr/lib/postgresql/11/lib'
/bin/mkdir -p '/usr/share/postgresql/11/extension'
/bin/mkdir -p '/usr/share/postgresql/11/extension'
/usr/bin/install -c -m 755  pg_libphonenumber.so '/usr/lib/postgresql/11/lib/pg_libphonenumber.so'
/usr/bin/install -c -m 644 .//pg_libphonenumber.control '/usr/share/postgresql/11/extension/'
/usr/bin/install -c -m 644 .//sql/pg_libphonenumber--*.sql  '/usr/share/postgresql/11/extension/'
/bin/mkdir -p '/usr/lib/postgresql/11/lib/bitcode/pg_libphonenumber'
/bin/mkdir -p '/usr/lib/postgresql/11/lib/bitcode'/pg_libphonenumber/src/
/usr/bin/install -c -m 644 src/error_handling.bc '/usr/lib/postgresql/11/lib/bitcode'/pg_libphonenumber/src/
/usr/bin/install -c -m 644 src/pg_libphonenumber.bc '/usr/lib/postgresql/11/lib/bitcode'/pg_libphonenumber/src/
/usr/bin/install -c -m 644 src/packed_phone_number.bc '/usr/lib/postgresql/11/lib/bitcode'/pg_libphonenumber/src/
cd '/usr/lib/postgresql/11/lib/bitcode' && /usr/lib/llvm-6.0/bin/llvm-lto -thinlto -thinlto-action=thinlink -o pg_libphonenumber.index.bc pg_libphonenumber/src/error_handling.bc pg_libphonenumber/src/pg_libphonenumber.bc pg_libphonenumber/src/packed_phone_number.bc
error: can't create module summary index for buffer: Expected a single module
LLVM ERROR: ThinLink didn't create an index
/usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk:229: recipe for target 'install' failed
make: *** [install] Error 1
```

I am using postgres 11 so that could be the issue? Is there a way to support 11 or is 9.4 the only supported version? Searching online, I find [this](https://github.com/PierreSenellart/provsql/issues/9) on a different project which leads to this [snippet](https://github.com/rdkit/rdkit/issues/2192#issuecomment-445579020) but copying that into the Makefile doesn't help. I don't know enough to understand the messages.

**Comment by blm768** [comment]
I'm seeing the same error if I try to upgrade the Docker image to PostgreSQL 11. According to the bug reports you linked to, it looks like it's likely an LLVM bug that affects the Postgres JIT. Adding `override with_llvm=no` seems to fix the problem for now; it'll disable JIT support, but assuming that the bug gets fixed in LLVM, that should start working again eventually.

**Comment by driftavalii** [comment]
Where did you add the `override with_llvm=no`. Is there a config file that should contain it?

**Comment by blm768** [comment]
Oh, I forgot to explain that part. That line goes near the top of the Makefile. The exact location doesn't matter too much; I think it just needs to go before the point where PGXS gets included.

**Comment by driftavalii** [comment]
Thanks!
